<a href="https://colab.research.google.com/github/riyawakde16-art/Day20/blob/main/Day20(Optional).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from google.colab import files
uploaded=files.upload()

Saving Colth.csv to Colth.csv

In [3]:
filepath='/content/Colth.csv'
df=pd.read_csv(filepath)
df

,Brand,Category,Color,Size,Material,Rating,Reviews,Discount,Stock,Price
0,Zara,Jacket,White,XL,Cotton,4.8,469,46,78,3820.48
1,H&M,Shirt,White,XL,Wool,3.7,410,38,123,3670.49
2,Puma,T-shirt,White,M,Wool,4.0,560,36,171,2402.28
3,H&M,Dress,White,XL,Polyester,4.4,402,49,3,2059.36
4,H&M,Dress,Green,L,Polyester,2.9,876,55,89,2289.26
...,...,...,...,...,...,...,...,...,...,...
495,Nike,Jeans,White,M,Polyester,3.0,830,33,57,781.54
496,Puma,Shirt,Green,XL,Cotton,2.6,388,38,68,1447.28
497,Nike,Shirt,Green,L,Cotton,3.3,352,38,155,4140.61
498,Nike,Jacket,White,XL,Polyester,4.1,956,32,61,1161.15
499,Nike,Dress,White,M,Cotton,4.8,908,17,168,2041.90

In [4]:
df.head()

,Brand,Category,Color,Size,Material,Rating,Reviews,Discount,Stock,Price
0,Zara,Jacket,White,XL,Cotton,4.8,469,46,78,3820.48
1,H&M,Shirt,White,XL,Wool,3.7,410,38,123,3670.49
2,Puma,T-shirt,White,M,Wool,4.0,560,36,171,2402.28
3,H&M,Dress,White,XL,Polyester,4.4,402,49,3,2059.36
4,H&M,Dress,Green,L,Polyester,2.9,876,55,89,2289.26

In [9]:
X = df.drop('Price', axis=1)
y = df['Price']
print("\nShape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (500, 9)
Shape of y: (500,)

In [12]:
cat_cols = X.select_dtypes(include=['object']).columns
cat_cols
X_encoded = pd.get_dummies(X, columns=cat_cols).astype(int)
X_encoded.head()

,Rating,Reviews,Discount,Stock,Brand_Adidas,Brand_H&M,Brand_Nike,Brand_Puma,Brand_Zara,Category_Dress,...,Color_Red,Color_White,Size_L,Size_M,Size_S,Size_XL,Material_Cotton,Material_Denim,Material_Polyester,Material_Wool
0,4,469,46,78,0,0,0,0,1,0,...,0,1,0,0,0,1,1,0,0,0
1,3,410,38,123,0,1,0,0,0,0,...,0,1,0,0,0,1,0,0,0,1
2,4,560,36,171,0,0,0,1,0,0,...,0,1,0,1,0,0,0,0,0,1
3,4,402,49,3,0,1,0,0,0,1,...,0,1,0,0,0,1,0,0,1,0
4,2,876,55,89,0,1,0,0,0,1,...,0,0,1,0,0,0,0,0,1,0

In [13]:
from sklearn.preprocessing import StandardScaler
num_cols = X_encoded.select_dtypes(include=np.number).columns
scaler = StandardScaler()
X_encoded[num_cols] = scaler.fit_transform(X_encoded[num_cols])
X_encoded.head()

,Rating,Reviews,Discount,Stock,Brand_Adidas,Brand_H&M,Brand_Nike,Brand_Puma,Brand_Zara,Category_Dress,...,Color_Red,Color_White,Size_L,Size_M,Size_S,Size_XL,Material_Cotton,Material_Denim,Material_Polyester,Material_Wool
0,0.952885,-0.198013,0.873896,-0.392749,-0.484322,-0.478018,-0.527989,-0.471693,1.861259,-0.496873,...,-0.518686,2.291288,-0.558870,-0.592749,-0.561951,1.678331,1.704773,-0.534179,-0.626704,-0.561951
1,-0.317628,-0.410923,0.360896,0.405161,-0.484322,2.091971,-0.527989,-0.471693,-0.537271,-0.496873,...,-0.518686,2.291288,-0.558870,-0.592749,-0.561951,1.678331,-0.586588,-0.534179,-0.626704,1.779513
2,0.952885,0.130373,0.232646,1.256265,-0.484322,-0.478018,-0.527989,2.120025,-0.537271,-0.496873,...,-0.518686,2.291288,-0.558870,1.687055,-0.561951,-0.595830,-0.586588,-0.534179,-0.626704,1.779513
3,0.952885,-0.439792,1.066271,-1.722599,-0.484322,2.091971,-0.527989,-0.471693,-0.537271,2.012587,...,-0.518686,2.291288,-0.558870,-0.592749,-0.561951,1.678331,-0.586588,-0.534179,1.595650,-0.561951
4,-1.588142,1.270702,1.451021,-0.197704,-0.484322,2.091971,-0.527989,-0.471693,-0.537271,2.012587,...,-0.518686,-0.436436,1.789324,-0.592749,-0.561951,-0.595830,-0.586588,-0.534179,1.595650,-0.561951

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y, test_size=0.33, random_state=42)
print("\nShapes:")
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

Shapes:
X_train: (335, 27)
X_test: (165, 27)
y_train: (335,)
y_test: (165,)

In [15]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)
print("\nIntercept:", model.intercept_)
print("Coefficients:", model.coef_)

Intercept: 2753.146135023758
Coefficients: [-200.93234785  -45.66530235  -39.70158928   22.26894975   50.82895672
   80.99567982  -21.20376711  -62.24112339  -44.81902468 -160.47519597
   12.08274557   45.38377152  100.65627509    2.43129764  155.94991084
 -117.90677516 -115.7992523    80.13141809   -1.29455151  111.20902675
  -83.28142483  -32.19714957    6.64410793  -30.45479852   28.22997245
   24.66973834  -22.34158144]

In [16]:
y_pred = model.predict(X_test)
print("\nFirst 10 Predictions:", y_pred[:10])
print("First 10 Actual:", y_test.values[:10])

First 10 Predictions: [2999.80276525 2997.65956722 2852.01616348 3209.10876079 2961.72830894
 2958.24521415 2561.26529986 2360.92846369 2453.26359338 2965.64401256]
First 10 Actual: [4129.99  561.85 1544.08 2267.29 4043.24 4676.82 3306.84 3939.98 3713.24
 3465.7 ]

In [17]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print("\nR2 Score:", r2)
if r2 > 0.8:
    print("Model is performing very well.")
elif r2 > 0.6:
    print("Model performance is good.")
else:
    print("Model needs improvement.")

R2 Score: -0.14281582163554174
Model needs improvement.

In [18]:
import joblib
joblib.dump(model, 'LR_cloth.pkl')
joblib.dump(scaler, 'scaler.pkl')
joblib.dump(X_encoded.columns.tolist(), 'columns.pkl')
print("\nModel and files saved successfully!")

Model and files saved successfully!